export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_TEMPPAYMNTLIST_SUCCESS = "SET_TEMPPAYMNTLIST_SUCCESS";
export const SET_TEMPPAYMNTLIST_FAIL = "SET_TEMPPAYMNTLIST_FAIL";
export const SET_CONTENTCNT_PERPAGE_SUCCESS = "SET_CONTENTCNT_PERPAGE_SUCCESS";

export const SET_PAGENUM_SUCCESS = "SET_PAGENUM_SUCCESS";
export const SET_CONTENT_EDITABLE_SUCCESS = "SET_CONTENT_EDITABLE_SUCCESS";
export const SET_CURRPAGELIST_SUCCESS = "SET_CURRPAGELIST_SUCCESS";
export const SET_PAYMNT_UPDATE_SUCCESS = "SET_PAYMNT_UPDATE_SUCCESS";
export const SET_TOTALCNT_SUCCESS = "SET_TOTALCNT_SUCCESS";
export const SET_GetPAYMNTHIS_SUCCESS = "SET_GetPAYMNTHIS_SUCCESS";
export const SET_SetPAYMNTHIS_SUCCESS = "SET_SetPAYMNTHIS_SUCCESS";











